export const CREATE_DATA = 'CREATE_DATA';
export const DATA_LIMIT = 'DATA_LIMIT';

export const SET_SLICK_GRID_COLUMNS_START = "SET_SLICK_GRID_COLUMNS_START";
export const SET_SLICK_GRID_COLUMNS = "SET_SLICK_GRID_COLUMNS";
export const SET_SLICK_GRID_OPTIONS = "SET_SLICK_GRID_OPTIONS";
export const SET_SLICK_GRID_DATA = "SET_SLICK_GRID_DATA";

